childcare/urls.py
from django.conf.urls import patterns, url
from childcare import views
from classroom import views as classroom_views
from newsboard import views as newsboard_views

urlpatterns = patterns('',
                       #childcare
                       url(r'^childcare/$', views.childcare, name='childcare_info'),
                       url(r'^childcare/update/$', views.childcare_update, name='childcare_update'),

                       #users
                       url(r'^childcare/users/invite/$', views.invite_users, name='invite_users'),
                       url(r'^childcare/managers/(?P<username>[\w\-]+)/remove/$', views.remove_manager, name='manager_remove'),
                       url(r'^childcare/employees/(?P<username>[\w\-]+)/remove/$', views.remove_employee, name='employee_remove'),
                       url(r'^childcare/parents/(?P<username>[\w\-]+)/remove/$', views.remove_parent, name='parent_remove'),
                       url(r'^childcare/managers/$', views.managers_list, name='manager_list'),
                       url(r'^childcare/employees/$', views.employees_list, name='employee_list'),
                       url(r'^childcare/parents/$', views.parents_list, name='parent_list'),

                       # classroom
                       url(r'^classroom/create/$', classroom_views.classroom_create, name='classroom_create'),
                       url(r'^classroom/$', classroom_views.classroom_list, name='classroom_list'),
                       url(r'^classroom/(?P<classroom_id>\d+)/delete/$', classroom_views.classroom_delete, name='classroom_delete'),
                       url(r'^classroom/(?P<classroom_id>\d+)/update/$', classroom_views.classroom_update, name='classroom_update'),

                       # diary
                       url(r'^diary/create/$', classroom_views.diary_create, name='diary_create'),
                       url(r'^diary/(?P<diary_id>\d+)/$', classroom_views.diary_detail, name='diary_detail'),
                       url(r'^diary/$', classroom_views.diary_section, name='diary_list'),
                       url(r'^diary/(?P<diary_id>\d+)/images/$', classroom_views.add_diary_images, name='diary_add_images'),
                       url(r'^diary/(?P<diary_id>\d+)/delete/$', classroom_views.diary_delete, name='diary_delete'),
                       url(r'^diary/(?P<diary_id>\d+)/update/$', classroom_views.diary_update, name='diary_update'),
                       url(r'^diary/(?P<diary_id>\d+)/image/(?P<image_id>\d+)/delete/$', classroom_views.diary_image_delete, name='diary_image_delete'),

                       # newsboard
                       url(r'^newsboard/create/$', newsboard_views.childcare_news_create, name='news_create'),
                       url(r'^newsboard/(?P<news_id>\d+)/$', newsboard_views.childcare_news_detail, name='news_detail'),
                       url(r'^newsboard/(?P<news_id>\d+)/images/$', newsboard_views.add_news_images, name='news_add_images'),
                       url(r'^newsboard/(?P<news_id>\d+)/files/$', newsboard_views.add_news_files, name='news_add_files'),
                       url(r'^newsboard/$', newsboard_views.newsboard_section, name='news_list'),
                       url(r'^newsboard/(?P<news_id>\d+)/delete/$', newsboard_views.childcare_news_delete, name='news_delete'),
                       url(r'^newsboard/(?P<news_id>\d+)/update/$', newsboard_views.childcare_news_update, name='news_update'),
                       url(r'^newsboard/(?P<news_id>\d+)/image/(?P<image_id>\d+)/delete/$', newsboard_views.news_image_delete, name='news_image_delete'),
                       url(r'^newsboard/(?P<news_id>\d+)/file/(?P<file_id>\d+)/delete/$', newsboard_views.news_file_delete, name='news_file_delete'),

                       # website
                       url(r'^website/page/create/$', views.website_page_create, name='page_create'),
                       url(r'^website/$', views.website_pages_list, name='page_list'),
                       url(r'^website/page/(?P<page_id>\d+)/files/$', views.add_page_files, name='page_add_files'),
                       url(r'^website/page/(?P<page_id>\d+)/delete/$', views.website_page_delete, name='page_delete'),
                       url(r'^website/page/(?P<page_id>\d+)/update/$', views.website_page_update, name='page_update'),
                       url(r'^website/page/(?P<page_id>\d+)/file/(?P<file_id>\d+)/delete/$', views.page_file_delete, name='page_file_delete'),
                       url(r'^website/page/about/edit/$', views.website_first_page_edit, name='about_edit'),
                       url(r'^website/theme/$', views.website_choose_theme, name='choose_theme'),

                       # gallery
                       url(r'^gallery/$', views.gallery_section, name='gallery'),
                       )

kindy/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from childcare import views as childcare_views
from django.conf import settings
from utils.deployment import is_local_env
from userena import views as userena_views

admin.autodiscover()

urlpatterns = patterns('',

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # home
    url(r'^$', 'kindy.views.home', name='home'),

    # accounts
    url(r'^accounts/', include('userena.urls')),
    url(r'^activate/(?P<activation_key>\w+)/$', userena_views.activate, {'success_url': '/'}, name='userena_activate'),

    #childcare
    url(r'^childcare/create/$', childcare_views.childcare_create, name='childcare_create'),
    url(r'^(?P<childcare_slug>[\w\-]+)/dashboard/', include('childcare.urls', namespace="childcare")),

    #website
    url(r'^(?P<childcare_slug>[\w\-]+)/', include('website.urls', namespace="website")),
)

# check if app is local or deployed on server
LOCAL_ENV_BOOL = is_local_env()

if LOCAL_ENV_BOOL:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

website/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from childcare.models import Childcare
from utils.imagegenerators import get_file_path
from utils.slugify import unique_slugify


class Page(models.Model):
    title = models.CharField(max_length=100, null=True)
    slug = models.SlugField(max_length=100, unique=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)
    content = models.TextField(null=True)
    childcare = models.ForeignKey(Childcare, null=True)
    order = models.SmallIntegerField(default=1, null=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['order']

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = unique_slugify(self, self.title)
        super(Page, self).save(*args, **kwargs)


class PageFile(models.Model):
    file = models.FileField(upload_to=get_file_path, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    uploader = models.ForeignKey(User, null=True)
    page = models.ForeignKey(Page, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

childcare/views.py
from itertools import chain
from operator import attrgetter
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from guardian.decorators import permission_required_or_403
from childcare.forms import ChildcareCreateForm, WebsitePageCreateForm, FirstPageForm, ChooseThemeForm, AddPageFileForm, ChildcareUpdateForm, InviteUsersForm
from childcare.models import Childcare, Theme
from classroom.models import Classroom, DiaryImage, Diary
from newsboard.models import News, NewsImage
from utils.invites import invite_new_kindy_user, add_current_user
from website.models import Page, PageFile
from django.forms.formsets import formset_factory

# setup logging
import logging
log = logging.getLogger("logentries")

log_prefix = '[kindylog]'


@login_required
def childcare_create(request):
    if request.method == 'POST':
        form = ChildcareCreateForm(request.POST)
        if form.is_valid():
            #managers = form.cleaned_data['managers']
            childcare = form.save(commit=False)
            # check if there is a default theme
            try:
                theme = get_object_or_404(Theme, pk=1)
                theme_exist = True
            except:
                theme_exist = False
            if theme_exist:
                childcare.theme = get_object_or_404(Theme, pk=1)  # set 1st theme as default
            else:
                theme = Theme(title='Default theme', computer_name='default', description='Default theme')
                theme.save()
                childcare.theme = theme
            childcare = form.save(commit=True)
            # automatically add current user as manager and give him permissions
            childcare.managers.add(request.user)
            managers = list(childcare.managers.all())
            # add manager permissions
            group = Group.objects.get(name='Childcare %s: Manager' % childcare.pk)
            for manager in managers:
                manager.groups.add(group)
            # create default classroom
            classroom = Classroom(name='%s classroom' % childcare, childcare=childcare)
            classroom.save()
            log.info(log_prefix+'Childcare created (childcare: %s, user: %s)' % (childcare.name, request.user))
            return HttpResponseRedirect(reverse('childcare:childcare_info', kwargs={'childcare_slug': childcare.slug}))
    else:
        form = ChildcareCreateForm()
    return render(request, 'childcare/childcare_create.html', {'form': form})


@login_required()
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def childcare_update(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    if request.method == 'POST':
        form = ChildcareUpdateForm(data=request.POST, instance=childcare)
        if form.is_valid():
            form.save()
            log.info(log_prefix+'Childcare updated (childcare: %s, user: %s)' % (childcare.name, request.user))
            return HttpResponseRedirect(reverse('childcare:childcare_info', kwargs={'childcare_slug': childcare.slug}))
    else:
        form = ChildcareUpdateForm(instance=childcare)
    return render(request, 'childcare/childcare_update.html', {'form': form,
                                                               'childcare': childcare})


@login_required
@permission_required_or_403('childcare_view', (Childcare, 'slug', 'childcare_slug'))
def childcare(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    log.info(log_prefix+'Childcare opened (childcare: %s, user: %s)' % (childcare.name, request.user))
    classroom_num = Classroom.objects.filter(childcare=childcare, disabled=False).count()
    manager_num = User.objects.filter(childcare_managers__id=childcare.pk).count()
    employee_num = User.objects.filter(childcare_employees__id=childcare.pk).count()
    parent_num = User.objects.filter(childcare_parents__id=childcare.pk).count()
    pages_num = Page.objects.filter(childcare=childcare).count()

    classroom_list = Classroom.objects.filter(childcare=childcare)
    diary_num = Diary.objects.filter(classroom__in=classroom_list).count()
    news_num = News.objects.filter(childcare=childcare).count()

    return render(request, 'childcare/childcare_detail.html', {'childcare': childcare,
                                                               'classroom_num': classroom_num,
                                                               'manager_num': manager_num,
                                                               'employee_num': employee_num,
                                                               'parent_num': parent_num,
                                                               'diary_num': diary_num,
                                                               'news_num': news_num,
                                                               'pages_num': pages_num})


@login_required()
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def website_page_create(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    if request.method == 'POST':
        form = WebsitePageCreateForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.childcare = childcare
            obj.save
            form.save(commit=True)
            log.info(log_prefix+'Page created (childcare: %s, user: %s)' % (childcare.name, request.user))
            return HttpResponseRedirect(reverse('childcare:page_list', kwargs={'childcare_slug': childcare.slug}))
    else:
        form = WebsitePageCreateForm()
    return render(request, 'childcare/website_page_create.html', {'form': form, 'childcare': childcare})


@login_required()
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def website_page_update(request, childcare_slug, page_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    page = get_object_or_404(Page, pk=page_id, childcare=childcare)
    if request.method == 'POST':
        form = WebsitePageCreateForm(data=request.POST, instance=page)
        if form.is_valid():
            form.save()
            log.info(log_prefix+'Page updated (%s: %s, user: %s)' % (childcare.name, page.title, request.user))
            return HttpResponseRedirect(reverse('childcare:page_list', kwargs={'childcare_slug': childcare.slug}))
    else:
        form = WebsitePageCreateForm(instance=page)
    return render(request, 'childcare/website_page_update.html', {'form': form,
                                                                  'childcare': childcare,
                                                                  'page': page})


@login_required()
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def website_page_delete(request, childcare_slug, page_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    page = get_object_or_404(Page, pk=page_id, childcare=childcare)
    if request.method == 'POST':
        page.delete()
        log.info(log_prefix+'Page deleted (childcare: %s, user: %s)' % (childcare.name, request.user))
        return HttpResponseRedirect(reverse('childcare:page_list', kwargs={'childcare_slug': childcare.slug}))
    return render(request, 'childcare/website_page_delete.html', {'childcare': childcare,
                                                                  'page': page})


@login_required
@permission_required_or_403('childcare_view', (Childcare, 'slug', 'childcare_slug'))
def website_pages_list(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    all_page_list = Page.objects.filter(childcare=childcare)

    paginator = Paginator(all_page_list, 10)
    page = request.GET.get('page')

    try:
        page_list = paginator.page(page)
    except PageNotAnInteger:
        page_list = paginator.page(1)
    except EmptyPage:
        page_list = paginator.page(paginator.num_pages)

    return render(request, 'childcare/website_page_list.html', {'childcare': childcare,
                                                                'page_list': page_list})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def add_page_files(request, childcare_slug, page_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    page = get_object_or_404(Page, pk=page_id)
    if request.method == 'POST':
        form = AddPageFileForm(request.POST, request.FILES)
        if form.is_valid():
            log.info(log_prefix+'Page files added (childcare: %s, user: %s)' % (childcare.name, request.user))
            obj = form.save(commit=False)
            if obj.file:  # save only forms with files
                obj.page = page
                obj.uploader = request.user
                obj.save()
                form.save(commit=True)
                return HttpResponseRedirect(reverse('childcare:page_list', kwargs={'childcare_slug': childcare.slug}))
    else:
        form = AddPageFileForm()
    return render(request, 'childcare/add_page_file.html', {'form': form,
                                                            'childcare': childcare})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def page_file_delete(request, childcare_slug, page_id, file_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    file = get_object_or_404(PageFile, pk=file_id, page=page_id)
    page = get_object_or_404(Page, pk=page_id)
    if request.method == 'POST':

templates/childcare/childcare_base.html
{% extends 'kindy/base.html' %}

{% block sidebar-title %}Dashboard{% endblock %}

{% block sidebar %}
	<li><a href="{% url 'childcare:childcare_info' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-info-sign"></span>Childcare info</a>
		{% if "/"|add:childcare.slug|add:"/dashboard/childcare/" in request.path %}
		{% if user in childcare.employees.all or user in childcare.managers.all %}
		<ul>
			<li><a href="{% url 'childcare:childcare_update' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-edit"></span>Update childcare</a></li>
            <li><a href="{% url 'childcare:invite_users' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-plus"></span>Invite users</a></li>
		</ul>
		{% endif %}
		{% endif %}
	</li>
	<li><a href="{% url 'childcare:classroom_list' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-eye-open"></span>Classrooms</a>
		{% if "/"|add:childcare.slug|add:"/dashboard/classroom/" in request.path %}
		{% if user in childcare.employees.all or user in childcare.managers.all %}
		<ul>
			<li><a href="{% url 'childcare:classroom_create' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-plus"></span>Add classroom</a></li>
		</ul>
		{% endif %}
		{% endif %}
	</li>
	<li><a href="{% url 'childcare:diary_list' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-list"></span>Diary list</a>
		{% if "/"|add:childcare.slug|add:"/dashboard/diary/" in request.path %}
		{% if user in childcare.employees.all or user in childcare.managers.all %}
		<ul>
			<li><a href="{% url 'childcare:diary_create' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-plus"></span>Add a diary</a></li>
		</ul>
		{% endif %}
		{% endif %}
	</li>
	<li><a href="{% url 'childcare:news_list' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-list-alt"></span>Newsboard</a>
		{% if "/"|add:childcare.slug|add:"/dashboard/newsboard/" in request.path %}
		{% if user in childcare.employees.all or user in childcare.managers.all %}
		<ul>
			<li><a href="{% url 'childcare:news_create' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-plus"></span>Add newsboard post</a></li>
		</ul>
		{% endif %}
		{% endif %}
	</li>
	{% if user in childcare.employees.all or user in childcare.managers.all %}
	<li><a href="{% url 'childcare:page_list' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-globe"></span>Website</a>
		{% if "/"|add:childcare.slug|add:"/dashboard/website/" in request.path %}
		<ul>
			<li><a href="{% url 'childcare:page_create' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-plus"></span>Add page</a></li>
			<li><a href="{% url 'childcare:choose_theme' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-th"></span>Choose theme</a></li>
			<li><a href="/{{ childcare.slug }}/" class="external" target="_blank"><span class="glyphicon glyphicon-globe"></span>Go to website</a></li>
		</ul>
		{% endif %}
	</li>
	{% endif %}
	<li><a href="{% url 'childcare:gallery' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-picture"></span>Gallery</a></li>
{% endblock %}

templates/childcare/employees_add.html
{% extends 'childcare/childcare_base.html' %}

{% block title %}Add employees{% endblock title %}

{% block breadcrumb %}
    <li><a href="/{{ childcare.slug }}/dashboard/">{{ childcare }}</a></li>
    <li>Add employee</li>
{% endblock %}

{% block action_header %}
{% endblock action_header %}

{% block content-title %}Add {{ childcare }} employees{% endblock %}

{% block content %}
    <p>Search by username</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>
{% endblock content %}

{% block footer %}
    {% include 'autocomplete_light/static.html' %}
{% endblock %}

templates/childcare/employees_list.html
{% extends 'childcare/childcare_base.html' %}

{% block title %}{{ childcare.name }} employees{% endblock title %}

{% block action %}
    {% if user in childcare.employees.all or user in childcare.managers.all %}
        <li><a href="{% url 'childcare:invite_users' childcare_slug=childcare.slug %}?role=Employee"><span class="glyphicon glyphicon-plus"></span> Invite employee</a></li>
    {% endif %}
{% endblock %}

{% block content-title %}{{ childcare }} employees{% endblock %}

{% block content %}
    {% if employees_list %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                {% if user in childcare.employees.all or user in childcare.managers.all %}
                    <th>Tools</th>
                {% endif %}
            </tr>
            {% for employee in employees_list %}
                <tr>
                    <td>
                        {% if employee.get_full_name %}
                        <a href="/accounts/{{ employee.username }}">{{ employee.get_full_name }}</a>
                        {% else %}
                        <a href="/accounts/{{ employee.username }}"><small>(name not set)</small></a>
                        {% endif %}
                    </td>
                    <td>
                        {{ employee.username }}
                    </td>
                    <td>
                        {{ employee.email }}
                    </td>
                    {% if user in childcare.employees.all or user in childcare.managers.all %}
                    <td>
                        <a href="{% url 'childcare:employee_remove' childcare_slug=childcare.slug username=employee %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if employees_list.has_previous %}
                <a href="?page={{ employees_list.previous_page_number }}">previous</a>
            {% endif %}

            {% if employees_list.has_other_pages %}
            <span class="current">
                Page {{ employees_list.number }} of {{ employees_list.paginator.num_pages }}
            </span>
            {% endif %}

            {% if employees_list.has_next %}
                <a href="?page={{ employees_list.next_page_number }}"> next</a>
            {% endif %}
        </span>
    </div>
    {% else %}
    <p>No employees added yet. <a href="{% url 'childcare:invite_users' childcare_slug=childcare.slug %}?role=Employee" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-plus"></span> Invite employee</a></p>
    {% endif %}
{% endblock content %}

templates/childcare/gallery_section.html
{% extends 'childcare/childcare_base.html' %}

{% block title %}Image gallery{% endblock title %}

{% block header %}
    {% if image_list %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/fancybox.css">
    {% endif %}
{% endblock %}

{% block content-title %}Image gallery{% endblock %}

{% block content %}
    {% if image_list %}
        {% for image in image_list %}
        <div class="pull-left">
            <a href="{{ image.image.url }}" class="fancybox" rel="gallery"><img src="{{ image.thumbnail }}"></a>
        </div>
        {% endfor %}
        <div class="clearfix"></div>
        <div class="pagination">
            <span class="step-links">
                {% if image_list.has_previous %}
                    <a href="?page={{ image_list.previous_page_number }}">previous</a>
                {% endif %}

                {% if image_list.has_other_pages %}
                <span class="current">
                    Page {{ image_list.number }} of {{ image_list.paginator.num_pages }}
                </span>
                {% endif %}

                {% if image_list.has_next %}
                    <a href="?page={{ image_list.next_page_number }}"> next</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        <p>No photos were uploaded yet.{% if user in childcare.employees.all or user in childcare.managers.all %} Add some to <a href="{% url 'childcare:diary_list' childcare_slug=childcare.slug %}">diary</a> or <a href="{% url 'childcare:news_list' childcare_slug=childcare.slug %}">news</a>.{% endif %}</p>
    {% endif %}
{% endblock content %}

{% block footer %}
    {% if image_list %}
    <script type="text/javascript">
        gallery('a.fancybox');
    </script>
    {% endif %}
{% endblock %}

templates/childcare/managers_list.html
{% extends 'childcare/childcare_base.html' %}

{% block title %}{{ childcare.name }} managers{% endblock title %}

{% block action %}
    {% if user in childcare.managers.all %}
        <li><a href="{% url 'childcare:invite_users' childcare_slug=childcare.slug %}?role=Manager"><span class="glyphicon glyphicon-plus"></span> Invite manager</a></li>
    {% endif %}
{% endblock %}

{% block content-title %}{{ childcare }} managers{% endblock %}

{% block content %}
    {% if managers_list %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                {% if user in childcare.managers.all %}
                <th>Tools</th>
                {% endif %}
            </tr>
            {% for manager in managers_list %}
                <tr>
                    <td>
                        {% if manager.get_full_name %}
                        <a href="/accounts/{{ manager.username }}">{{ manager.first_name }} {{ manager.last_name }}</a>
                        {% else %}
                        <a href="/accounts/{{ manager.username }}"><small>(name not set)</small></a>
                        {% endif %}
                    </td>
                    <td>
                        {{ manager.username }}
                    </td>
                    <td>
                        {{ manager.email }}
                    </td>
                    {% if user in childcare.managers.all %}
                    <td>
                        <a href="{% url 'childcare:manager_remove' childcare_slug=childcare.slug username=manager %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if managers_list.has_previous %}
                <a href="?page={{ managers_list.previous_page_number }}">previous</a>
            {% endif %}

            {% if managers_list.has_other_pages %}
            <span class="current">
                Page {{ managers_list.number }} of {{ managers_list.paginator.num_pages }}
            </span>
            {% endif %}

            {% if managers_list.has_next %}
                <a href="?page={{ managers_list.next_page_number }}"> next</a>
            {% endif %}
        </span>
    </div>
    {% else %}
    <p>No managers.</p>
    {% endif %}
{% endblock content %}

templates/childcare/parents_list.html
{% extends 'childcare/childcare_base.html' %}

{% block title %}{{ childcare.name }} parents{% endblock title %}

{% block action %}
    {% if user in childcare.employees.all or user in childcare.managers.all %}
        <li><a href="{% url 'childcare:invite_users' childcare_slug=childcare.slug %}?role=Parent"><span class="glyphicon glyphicon-plus"></span> Invite parent</a></li>
    {% endif %}
{% endblock %}

{% block content-title %}{{ childcare }} parents{% endblock %}

{% block content %}
    {% if parents_list %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>Name</th>
                <th>Username</th>
                <th>Email</th>
                {% if user in childcare.employees.all or user in childcare.managers.all %}
                    <th>Tools</th>
                {% endif %}
            </tr>
            {% for parent in parents_list %}
                <tr>
                    <td>
                        {% if parent.get_full_name %}
                        <a href="/accounts/{{ parent.username }}">{{ parent.get_full_name }}</a>
                        {% else %}
                        <a href="/accounts/{{ parent.username }}"><small>(name not set)</small></a>
                        {% endif %}
                    </td>
                    <td>
                        {{ parent.username }}
                    </td>
                    <td>
                        {{ parent.email }}
                    </td>
                    {% if user in childcare.employees.all or user in childcare.managers.all %}
                    <td>
                        <a href="{% url 'childcare:parent_remove' childcare_slug=childcare.slug username=parent %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if parents_list.has_previous %}
                <a href="?page={{ parents_list.previous_page_number }}">previous</a>
            {% endif %}

            {% if parents_list.has_other_pages %}
            <span class="current">
                Page {{ parents_list.number }} of {{ parents_list.paginator.num_pages }}
            </span>
            {% endif %}

            {% if parents_list.has_next %}
                <a href="?page={{ parents_list.next_page_number }}"> next</a>
            {% endif %}
        </span>
    </div>
    {% else %}
    <p>No parents added yet. <a href="{% url 'childcare:invite_users' childcare_slug=childcare.slug %}?role=Parent" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-plus"></span> Invite parent</a></p>
    {% endif %}
{% endblock content %}