childcare/urls.py
from django.conf.urls import patterns, url
from childcare import views
from classroom import views as classroom_views
from newsboard import views as newsboard_views

urlpatterns = patterns('',
                       #childcare
                       url(r'^childcare/$', views.childcare, name='childcare_info'),
                       url(r'^childcare/update/$', views.childcare_update, name='childcare_update'),

                       #users
                       url(r'^childcare/users/invite/$', views.invite_users, name='invite_users'),
                       url(r'^childcare/managers/(?P<username>[\w\-]+)/remove/$', views.remove_manager, name='manager_remove'),
                       url(r'^childcare/employees/(?P<username>[\w\-]+)/remove/$', views.remove_employee, name='employee_remove'),
                       url(r'^childcare/parents/(?P<username>[\w\-]+)/remove/$', views.remove_parent, name='parent_remove'),
                       url(r'^childcare/managers/$', views.managers_list, name='manager_list'),
                       url(r'^childcare/employees/$', views.employees_list, name='employee_list'),
                       url(r'^childcare/parents/$', views.parents_list, name='parent_list'),

                       # classroom
                       url(r'^classroom/create/$', classroom_views.classroom_create, name='classroom_create'),
                       url(r'^classroom/$', classroom_views.classroom_list, name='classroom_list'),
                       url(r'^classroom/(?P<classroom_id>\d+)/delete/$', classroom_views.classroom_delete, name='classroom_delete'),
                       url(r'^classroom/(?P<classroom_id>\d+)/update/$', classroom_views.classroom_update, name='classroom_update'),

                       # diary
                       url(r'^diary/create/$', classroom_views.diary_create, name='diary_create'),
                       url(r'^diary/(?P<diary_id>\d+)/$', classroom_views.diary_detail, name='diary_detail'),
                       url(r'^diary/$', classroom_views.diary_section, name='diary_list'),
                       url(r'^diary/(?P<diary_id>\d+)/images/$', classroom_views.add_diary_images, name='diary_add_images'),
                       url(r'^diary/(?P<diary_id>\d+)/delete/$', classroom_views.diary_delete, name='diary_delete'),
                       url(r'^diary/(?P<diary_id>\d+)/update/$', classroom_views.diary_update, name='diary_update'),
                       url(r'^diary/(?P<diary_id>\d+)/image/(?P<image_id>\d+)/delete/$', classroom_views.diary_image_delete, name='diary_image_delete'),

                       # newsboard
                       url(r'^newsboard/create/$', newsboard_views.childcare_news_create, name='news_create'),
                       url(r'^newsboard/(?P<news_id>\d+)/$', newsboard_views.childcare_news_detail, name='news_detail'),
                       url(r'^newsboard/(?P<news_id>\d+)/images/$', newsboard_views.add_news_images, name='news_add_images'),
                       url(r'^newsboard/(?P<news_id>\d+)/files/$', newsboard_views.add_news_files, name='news_add_files'),
                       url(r'^newsboard/$', newsboard_views.newsboard_section, name='news_list'),
                       url(r'^newsboard/(?P<news_id>\d+)/delete/$', newsboard_views.childcare_news_delete, name='news_delete'),
                       url(r'^newsboard/(?P<news_id>\d+)/update/$', newsboard_views.childcare_news_update, name='news_update'),
                       url(r'^newsboard/(?P<news_id>\d+)/image/(?P<image_id>\d+)/delete/$', newsboard_views.news_image_delete, name='news_image_delete'),
                       url(r'^newsboard/(?P<news_id>\d+)/file/(?P<file_id>\d+)/delete/$', newsboard_views.news_file_delete, name='news_file_delete'),

                       # website
                       url(r'^website/page/create/$', views.website_page_create, name='page_create'),
                       url(r'^website/$', views.website_pages_list, name='page_list'),
                       url(r'^website/page/(?P<page_id>\d+)/files/$', views.add_page_files, name='page_add_files'),
                       url(r'^website/page/(?P<page_id>\d+)/delete/$', views.website_page_delete, name='page_delete'),
                       url(r'^website/page/(?P<page_id>\d+)/update/$', views.website_page_update, name='page_update'),
                       url(r'^website/page/(?P<page_id>\d+)/file/(?P<file_id>\d+)/delete/$', views.page_file_delete, name='page_file_delete'),
                       url(r'^website/page/about/edit/$', views.website_first_page_edit, name='about_edit'),
                       url(r'^website/theme/$', views.website_choose_theme, name='choose_theme'),

                       # gallery
                       url(r'^gallery/$', views.gallery_section, name='gallery'),
                       )

kindy/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from childcare import views as childcare_views
from django.conf import settings
from utils.deployment import is_local_env
from userena import views as userena_views

admin.autodiscover()

urlpatterns = patterns('',

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # home
    url(r'^$', 'kindy.views.home', name='home'),

    # accounts
    url(r'^accounts/', include('userena.urls')),
    url(r'^activate/(?P<activation_key>\w+)/$', userena_views.activate, {'success_url': '/'}, name='userena_activate'),

    #childcare
    url(r'^childcare/create/$', childcare_views.childcare_create, name='childcare_create'),
    url(r'^(?P<childcare_slug>[\w\-]+)/dashboard/', include('childcare.urls', namespace="childcare")),

    #website
    url(r'^(?P<childcare_slug>[\w\-]+)/', include('website.urls', namespace="website")),
)

# check if app is local or deployed on server
LOCAL_ENV_BOOL = is_local_env()

if LOCAL_ENV_BOOL:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

newsboard/models.py
from django.contrib.auth.models import User
from django.db import models, IntegrityError
from childcare.models import Childcare
from utils.imagegenerators import get_file_path
from utils.slugify import unique_slugify


class News(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    created = models.DateTimeField(auto_now_add=True)  # null=True
    modified = models.DateTimeField(auto_now=True)  # null=True
    author = models.ForeignKey(User)
    content = models.TextField()
    childcare = models.ForeignKey(Childcare)
    public = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created']

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = unique_slugify(self, self.title)
        super(News, self).save(*args, **kwargs)


class NewsImage(models.Model):
    image = models.ImageField(upload_to=get_file_path, blank=True)
    thumbnail = models.CharField(max_length=255, null=True)
    news = models.ForeignKey(News)
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)
    uploader = models.ForeignKey(User, null=True)


class NewsFile(models.Model):
    file = models.FileField(upload_to=get_file_path)
    description = models.CharField(max_length=500, blank=True)
    uploader = models.ForeignKey(User)
    news = models.ForeignKey(News)
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)

newsboard/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from guardian.decorators import permission_required_or_403
from childcare.models import Childcare
from newsboard.forms import NewsCreateForm, AddNewsImageForm, AddNewsFileForm, NewsUpdateForm
from newsboard.models import News, NewsImage, NewsFile
from django.forms.formsets import formset_factory
from utils.files_images import get_max_size_in_mb
from utils.imagegenerators import utils_generate_thumbnail

# setup logging
import logging
log = logging.getLogger("logentries")
log_prefix = '[kindylog]'


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def childcare_news_create(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    if request.method == 'POST':
        form = NewsCreateForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = request.user
            obj.childcare = childcare
            obj.save()
            news = form.save(commit=True)
            log.info(log_prefix+'News created (childcare: %s, user: %s)' % (childcare.name, request.user))
            return HttpResponseRedirect(reverse('childcare:news_detail', kwargs={'childcare_slug': childcare.slug,
                                                                               'news_id': news.pk}))
    else:
        form = NewsCreateForm()
    return render(request, 'newsboard/childcare_news_create.html', {'form': form, 'childcare': childcare})


@login_required
@permission_required_or_403('childcare_view', (Childcare, 'slug', 'childcare_slug'))
def childcare_news_detail(request, childcare_slug, news_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    news = get_object_or_404(News, pk=news_id, childcare=childcare)
    news_image_list = NewsImage.objects.filter(news=news)
    news_file_list = NewsFile.objects.filter(news=news)
    return render(request, 'newsboard/childcare_news_detail.html', {'childcare': childcare,
                                                                    'news': news,
                                                                    'news_image_list': news_image_list,
                                                                    'news_file_list': news_file_list})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def childcare_news_update(request, childcare_slug, news_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    news = get_object_or_404(News, pk=news_id, childcare=childcare)
    if request.method == 'POST':
        form = NewsUpdateForm(data=request.POST, instance=news)
        if form.is_valid():
            form.save()
            log.info(log_prefix+'News updated (childcare: %s, user: %s)' % (childcare.name, request.user))
            return HttpResponseRedirect(reverse('childcare:news_detail', kwargs={'childcare_slug': childcare.slug,
                                                                                 'news_id': news.pk}))
    else:
        form = NewsUpdateForm(instance=news)
    return render(request, 'newsboard/childcare_news_update.html', {'form': form,
                                                                    'childcare': childcare,
                                                                    'news': news})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def childcare_news_delete(request, childcare_slug, news_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    news = get_object_or_404(News, pk=news_id, childcare=childcare)
    if request.method == 'POST':
        news.delete()
        log.info(log_prefix+'News deleted (childcare: %s, user: %s)' % (childcare.name, request.user))
        return HttpResponseRedirect(reverse('childcare:news_list', kwargs={'childcare_slug': childcare.slug}))
    return render(request, 'newsboard/childcare_news_delete.html', {'childcare': childcare,
                                                                    'news': news})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def add_news_images(request, childcare_slug, news_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    news = get_object_or_404(News, pk=news_id)
    image_size = get_max_size_in_mb()
    if request.method == 'POST':
        form = AddNewsImageForm(request.POST, request.FILES)
        if form.is_valid():
            log.info(log_prefix+'News images added (childcare: %s, user: %s)' % (childcare.name, request.user))
            obj = form.save(commit=False)
            if obj.image:  # save only forms with images
                obj.news = news
                obj.uploader = request.user
                obj.save()
                object = form.save(commit=True)
                # generate thumbnail
                utils_generate_thumbnail(object)
                return HttpResponseRedirect(reverse('childcare:news_detail', kwargs={'childcare_slug': childcare.slug,
                                                                                 'news_id': news.pk}))
    else:
        form = AddNewsImageForm()
    return render(request, 'newsboard/add_news_image.html', {'form': form,
                                                             'childcare': childcare,
                                                             'image_size': image_size})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def news_image_delete(request, childcare_slug, news_id, image_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    image = get_object_or_404(NewsImage, pk=image_id, news=news_id)
    news = get_object_or_404(News, pk=news_id)
    if request.method == 'POST':
        image.delete()
        log.info(log_prefix+'News image deleted (childcare: %s, user: %s)' % (childcare.name, request.user))
        return HttpResponseRedirect(reverse('childcare:news_detail', kwargs={'childcare_slug': childcare.slug,
                                                                             'news_id': news.pk}))
    return render(request, 'newsboard/news_image_delete.html', {'childcare': childcare,
                                                                'image': image})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def add_news_files(request, childcare_slug, news_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    news = get_object_or_404(News, pk=news_id)
    file_size = get_max_size_in_mb()
    if request.method == 'POST':
        form = AddNewsFileForm(request.POST, request.FILES)
        if form.is_valid():
            log.info(log_prefix+'News files added (childcare: %s, user: %s)' % (childcare.name, request.user))
            obj = form.save(commit=False)
            if obj.file:  # save only forms with files
                obj.news = news
                obj.uploader = request.user
                obj.save()
                form.save(commit=True)
                return HttpResponseRedirect(reverse('childcare:news_detail', kwargs={'childcare_slug': childcare.slug,
                                                                                     'news_id': news.pk}))
    else:
        form = AddNewsFileForm()
    return render(request, 'newsboard/add_news_file.html', {'form': form,
                                                            'childcare': childcare,
                                                            'file_size': file_size})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def news_file_delete(request, childcare_slug, news_id, file_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    file = get_object_or_404(NewsFile, pk=file_id, news=news_id)
    news = get_object_or_404(News, pk=news_id)
    if request.method == 'POST':
        file.delete()
        log.info(log_prefix+'News file deleted (childcare: %s, user: %s)' % (childcare.name, request.user))
        return HttpResponseRedirect(reverse('childcare:news_detail', kwargs={'childcare_slug': childcare.slug,
                                                                             'news_id': news.pk}))
    return render(request, 'newsboard/news_file_delete.html', {'childcare': childcare,
                                                               'file': file})


@login_required()
@permission_required_or_403('childcare_view', (Childcare, 'slug', 'childcare_slug'))
def newsboard_section(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    all_news_list = News.objects.filter(childcare=childcare)
    log.info(log_prefix+'Newsboard (childcare: %s, user: %s)' % (childcare.name, request.user))

    paginator = Paginator(all_news_list, 10)
    page = request.GET.get('page')

    try:
        news_list = paginator.page(page)
    except PageNotAnInteger:
        news_list = paginator.page(1)
    except EmptyPage:
        news_list = paginator.page(paginator.num_pages)

    return render(request, 'newsboard/newsboard_section.html', {'childcare': childcare, 'news_list': news_list})

templates/newsboard/add_news_file.html
{% extends 'childcare/childcare_base.html' %}
{% load widget_tweaks %}

{% block title %}Add news files{% endblock title %}

{% block content-title %}Add news files{% endblock %}

{% block content %}
  <p>File has to be <strong>smaller than {{ file_size }} MB</strong>. You can upload one file at once (and add more later).</p>
  <form method="post" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
      {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label class="col-md-2 control-label">{{ field.label }}</label>
        <div class="col-md-3">
          {% if field.name == 'file' %}
          {{ field|add_class:'form-control-static' }}
          {% else %}
          {{ field|add_class:'form-control' }}
          {% endif %}
        </div>
        <div class="col-md-3">
          <p class="form-control-static">{{ field.errors.as_text }}</p>
        </div>
      </div>
      {% endfor %}
    <div class="form-group">
      <div class="col-md-2 col-md-offset-2">
        <input type="submit" value="Upload" class="btn btn-success">
      </div>
    </div>
  </form>
{% endblock content %}

templates/newsboard/childcare_news_create.html
{% extends 'childcare/childcare_base.html' %}
{% load widget_tweaks %}

{% block title %}Create newsboard post{% endblock %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/texteditor.css">
{% endblock %}

{% block content-title %}Create newsboard post{% endblock %}

{% block content %}
<form method="post" class="form-horizontal">
	{% csrf_token %}
	{% for field in form %}
	{% comment %} Displaying checkboxes differently {% endcomment %}
	{% if field.name == 'public' %}
	<div class="form-group">
		<div class="col-md-3 col-md-offset-1">
			<div class="checkbox">
				<label>
					{{ field }} {{ field.label }}
				</label>
			</div>
		</div>
	</div>
	{% else %}
	<div class="form-group{% if field.errors %} has-error{% endif %}">
		<label class="col-md-1 control-label">{{ field.label }}</label>
		<div class="col-md-3">
			{{ field|add_class:'form-control' }}

			{% if field.name == 'content' and field.errors %}
			<p>{{ field.errors.as_text }}</p>
			{% endif %}
		</div>
		{% if field.name != 'content' %}
		<div class="col-md-3">
			<p class="form-control-static">{{ field.errors.as_text }}</p>
		</div>
		{% endif %}
	</div>
	{% endif %}
	{% endfor %}
	<div class="form-group">
		<div class="col-md-2 col-md-offset-1">
			<input type="submit" value="Create" class="btn btn-success">
		</div>
	</div>
</form>
{% endblock %}

{% block footer %}
	<script type="text/javascript">
		texteditor('#id_content');
	</script>
{% endblock %}

templates/newsboard/childcare_news_delete.html
{% extends 'childcare/childcare_base.html' %}
{% block title %}Delete news{% endblock title %}

{% block breadcrumb %}
    <li><a href="/{{ childcare.slug }}/dashboard/newsboard/">Newsboard</a></li>
    <li>Delete</li>
{% endblock %}

{% block action_header %}
{% endblock action_header %}

{% block content-title %}Delete news {{ news }}?{% endblock %}

{% block content %}
    <p>Are you sure you want to delete news {{ news }}?</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, I'm sure</button>
    </form>
{% endblock content %}

templates/newsboard/childcare_news_detail.html
{% extends 'childcare/childcare_base.html' %}
{% load thumbnail %}

{% block header %}
    {% if news_image_list %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/fancybox.css">
    {% endif %}
{% endblock %}

{% block title %}{{ news }}{% endblock title %}

{% block action %}
    {% if user in childcare.employees.all or user in childcare.managers.all %}
        <li><a href="{% url 'childcare:news_add_images' childcare_slug=childcare.slug news_id=news.pk %}"><span class="glyphicon glyphicon-picture"></span> Add images</a></li>
        <li><a href="{% url 'childcare:news_add_files' childcare_slug=childcare.slug news_id=news.pk %}"><span class="glyphicon glyphicon-cloud-upload"></span> Add files</a></li>
        <li><a href="{% url 'childcare:news_update' childcare_slug=childcare.slug news_id=news.pk %}"><span class="glyphicon glyphicon-edit"></span> Update</a></li>
        <li><a href="{% url 'childcare:news_delete' childcare_slug=childcare.slug news_id=news.pk %}"><span class="glyphicon glyphicon-remove"></span> Delete</a></li>
    {% endif %}
{% endblock action %}

{% block content-title %}{{ news }}{% endblock %}

{% block content %}
    <p><strong>{% if news.author.first_name == '' %} {{ news.author }}{% else %} {{ news.author.get_full_name }}{% endif %} | {{ news.created }}</strong></p>
    <p>{{ news.content|safe }}</p>

    {% if news_image_list %}
    <hr>
    <p><strong>Gallery</strong></p>
        {% for image in news_image_list %}
            {% if image.image %}
                <div class="pull-left">
                    <a href="{{ image.image.url }}" class="fancybox" rel="gallery" title="{{ news }}"><img src="{{ image.thumbnail }}"></a>

                    {% if user in childcare.employees.all or user in childcare.managers.all %}
                        <p><a href="{% url 'childcare:news_image_delete' childcare_slug=childcare.slug news_id=news.pk image_id=image.pk %}"><span class="glyphicon glyphicon-remove"></span> Delete</a></p>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}
        <div class="clearfix"></div>
    {% else %}
        {% if user in childcare.employees.all or user in childcare.managers.all %}
        <hr>
        <p><strong>Gallery</strong></p>
        No images were added yet to this news. <a href="{% url 'childcare:news_add_images' childcare_slug=childcare.slug news_id=news.pk %}" class="btn btn-xs btn-default">Add images</a>
        {% endif %}
    {% endif %}

    {% if news_file_list %}
    <hr>
    <p><strong>Attachments</strong></p>
        Files:<ul>
        {% for file in news_file_list %}
            {% if file.file %}
                <li><a href="{{ file.file.url }}">{{ file.description }}</a>, {% if file.uploader.first_name == '' %} {{ file.uploader }}{% else %} {{ file.uploader.get_full_name }}{% endif %} ({{ file.created }})
                    {% if user in childcare.employees.all or user in childcare.managers.all %}
                        | <a href="{% url 'childcare:news_file_delete' childcare_slug=childcare.slug news_id=news.pk file_id=file.pk %}">Delete</a></li>
                    {% endif %}
                {% endif %}
        {% endfor %}
        </ul>
    {% else %}
        {% if user in childcare.employees.all or user in childcare.managers.all %}
        <div class="clearfix"></div>
        <hr>
        <p><strong>Attachments</strong></p>
        No attachments were added yet to this news. <a href="{% url 'childcare:news_add_files' childcare_slug=childcare.slug news_id=news.pk %}" class="btn btn-xs btn-default">Add attachments</a>
        {% endif %}
    {% endif %}
{% endblock content %}

{% block footer %}
    {% if news_image_list %}
    <script type="text/javascript">
        gallery('a.fancybox');
    </script>
    {% endif %}
{% endblock %}

templates/newsboard/childcare_news_update.html
{% extends 'childcare/childcare_base.html' %}
{% load widget_tweaks %}

{% block title %}Update newsboard post{% endblock title %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/texteditor.css">
{% endblock %}

{% block content-title %}Update newsboard post {{ news }}{% endblock %}

{% block content %}
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js"></script>
<form method="post" class="form-horizontal">
	{% csrf_token %}
	{% for field in form %}
	{% comment %} Displaying checkboxes differently {% endcomment %}
	{% if field.name == 'public' %}
	<div class="form-group">
		<div class="col-md-3 col-md-offset-1">
			<div class="checkbox">
				<label>
					{{ field }} {{ field.label }}
				</label>
			</div>
		</div>
	</div>
	{% else %}
	<div class="form-group{% if field.errors %} has-error{% endif %}">
		<label class="col-md-1 control-label">{{ field.label }}</label>
		<div class="col-md-3">
			{{ field|add_class:'form-control' }}
		</div>
		{% if field.name != 'content' %}
		<div class="col-md-3">
			<p class="form-control-static">{{ field.errors.as_text }}</p>
		</div>
		{% endif %}
	</div>
	{% if field.name == 'content' and field.errors %}
	<div class="form-group">
		<div class="col-md-3 col-md-offset-1">
			<p class="form-control-static">{{ field.errors.as_text }}</p>
		</div>
	</div>
	{% endif %}
	{% endif %}
	{% endfor %}
	<div class="form-group">
		<div class="col-md-2 col-md-offset-1">
			<input type="submit" value="Update" class="btn btn-success">
		</div>
	</div>
</form>
{% endblock %}

{% block footer %}
	<script type="text/javascript">
		texteditor('#id_content');
	</script>
{% endblock %}

templates/newsboard/newsboard_section.html
{% extends 'childcare/childcare_base.html' %}
{% block title %}{{ childcare }} newsboard{% endblock title %}

{% block breadcrumb %}
    <li>Newsboard</li>
{% endblock %}

{% block action %}
    {% if user in childcare.employees.all or user in childcare.managers.all %}
        <li><a href="{% url 'childcare:news_create' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-plus"></span> Add newsboard post</a></li>
    {% endif %}
{% endblock %}

{% block content-title %}Newsboard{% endblock %}

{% block content %}
    {% if news_list %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>Title</th>
                <th>Date</th>
                {% if user in childcare.employees.all or user in childcare.managers.all %}
                <th>Tools</th>
                <th>Visibility</th>
                {% endif %}
            </tr>
            {% for news in news_list %}
                <tr>
                    <td>
                        <a href="{% url 'childcare:news_detail' childcare_slug=childcare.slug news_id=news.pk %}">{{ news }}</a>
                    </td>
                    <td>
                        {{ news.created }}
                    </td>
                    {% if user in childcare.employees.all or user in childcare.managers.all %}
                    <td>
                        <a href="{% url 'childcare:news_add_images' childcare_slug=childcare.slug news_id=news.pk %}" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-plus"></span> Add images</a>
                        <a href="{% url 'childcare:news_add_files' childcare_slug=childcare.slug news_id=news.pk %}" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-cloud-upload"></span> Add files</a>
                        <a href="{% url 'childcare:news_update' childcare_slug=childcare.slug news_id=news.pk %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit"></span> Update</a>
                        <a href="{% url 'childcare:news_delete' childcare_slug=childcare.slug news_id=news.pk %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
                    </td>
                    <td>
                        {% if news.public %}
                            On website.
                        {% else %}
                            For registered users only.
                        {% endif %}
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if news_list.has_previous %}
                <a href="?page={{ news_list.previous_page_number }}">previous</a>
            {% endif %}

            {% if news_list.has_other_pages %}
            <span class="current">
                Page {{ news_list.number }} of {{ news_list.paginator.num_pages }}
            </span>
            {% endif %}

            {% if news_list.has_next %}
                <a href="?page={{ news_list.next_page_number }}"> next</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <p>No news yet.{% if user in childcare.employees.all or user in childcare.managers.all %} <a href="{% url 'childcare:news_create' childcare_slug=childcare.slug %}">Write your first news.</a>{% endif %}</p>
    {% endif %}
{% endblock content %}