childcare/urls.py
from django.conf.urls import patterns, url
from childcare import views
from classroom import views as classroom_views
from newsboard import views as newsboard_views

urlpatterns = patterns('',
                       #childcare
                       url(r'^childcare/$', views.childcare, name='childcare_info'),
                       url(r'^childcare/update/$', views.childcare_update, name='childcare_update'),

                       #users
                       url(r'^childcare/users/invite/$', views.invite_users, name='invite_users'),
                       url(r'^childcare/managers/(?P<username>[\w\-]+)/remove/$', views.remove_manager, name='manager_remove'),
                       url(r'^childcare/employees/(?P<username>[\w\-]+)/remove/$', views.remove_employee, name='employee_remove'),
                       url(r'^childcare/parents/(?P<username>[\w\-]+)/remove/$', views.remove_parent, name='parent_remove'),
                       url(r'^childcare/managers/$', views.managers_list, name='manager_list'),
                       url(r'^childcare/employees/$', views.employees_list, name='employee_list'),
                       url(r'^childcare/parents/$', views.parents_list, name='parent_list'),

                       # classroom
                       url(r'^classroom/create/$', classroom_views.classroom_create, name='classroom_create'),
                       url(r'^classroom/$', classroom_views.classroom_list, name='classroom_list'),
                       url(r'^classroom/(?P<classroom_id>\d+)/delete/$', classroom_views.classroom_delete, name='classroom_delete'),
                       url(r'^classroom/(?P<classroom_id>\d+)/update/$', classroom_views.classroom_update, name='classroom_update'),

                       # diary
                       url(r'^diary/create/$', classroom_views.diary_create, name='diary_create'),
                       url(r'^diary/(?P<diary_id>\d+)/$', classroom_views.diary_detail, name='diary_detail'),
                       url(r'^diary/$', classroom_views.diary_section, name='diary_list'),
                       url(r'^diary/(?P<diary_id>\d+)/images/$', classroom_views.add_diary_images, name='diary_add_images'),
                       url(r'^diary/(?P<diary_id>\d+)/delete/$', classroom_views.diary_delete, name='diary_delete'),
                       url(r'^diary/(?P<diary_id>\d+)/update/$', classroom_views.diary_update, name='diary_update'),
                       url(r'^diary/(?P<diary_id>\d+)/image/(?P<image_id>\d+)/delete/$', classroom_views.diary_image_delete, name='diary_image_delete'),

                       # newsboard
                       url(r'^newsboard/create/$', newsboard_views.childcare_news_create, name='news_create'),
                       url(r'^newsboard/(?P<news_id>\d+)/$', newsboard_views.childcare_news_detail, name='news_detail'),
                       url(r'^newsboard/(?P<news_id>\d+)/images/$', newsboard_views.add_news_images, name='news_add_images'),
                       url(r'^newsboard/(?P<news_id>\d+)/files/$', newsboard_views.add_news_files, name='news_add_files'),
                       url(r'^newsboard/$', newsboard_views.newsboard_section, name='news_list'),
                       url(r'^newsboard/(?P<news_id>\d+)/delete/$', newsboard_views.childcare_news_delete, name='news_delete'),
                       url(r'^newsboard/(?P<news_id>\d+)/update/$', newsboard_views.childcare_news_update, name='news_update'),
                       url(r'^newsboard/(?P<news_id>\d+)/image/(?P<image_id>\d+)/delete/$', newsboard_views.news_image_delete, name='news_image_delete'),
                       url(r'^newsboard/(?P<news_id>\d+)/file/(?P<file_id>\d+)/delete/$', newsboard_views.news_file_delete, name='news_file_delete'),

                       # website
                       url(r'^website/page/create/$', views.website_page_create, name='page_create'),
                       url(r'^website/$', views.website_pages_list, name='page_list'),
                       url(r'^website/page/(?P<page_id>\d+)/files/$', views.add_page_files, name='page_add_files'),
                       url(r'^website/page/(?P<page_id>\d+)/delete/$', views.website_page_delete, name='page_delete'),
                       url(r'^website/page/(?P<page_id>\d+)/update/$', views.website_page_update, name='page_update'),
                       url(r'^website/page/(?P<page_id>\d+)/file/(?P<file_id>\d+)/delete/$', views.page_file_delete, name='page_file_delete'),
                       url(r'^website/page/about/edit/$', views.website_first_page_edit, name='about_edit'),
                       url(r'^website/theme/$', views.website_choose_theme, name='choose_theme'),

                       # gallery
                       url(r'^gallery/$', views.gallery_section, name='gallery'),
                       )

kindy/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from childcare import views as childcare_views
from django.conf import settings
from utils.deployment import is_local_env
from userena import views as userena_views

admin.autodiscover()

urlpatterns = patterns('',

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # home
    url(r'^$', 'kindy.views.home', name='home'),

    # accounts
    url(r'^accounts/', include('userena.urls')),
    url(r'^activate/(?P<activation_key>\w+)/$', userena_views.activate, {'success_url': '/'}, name='userena_activate'),

    #childcare
    url(r'^childcare/create/$', childcare_views.childcare_create, name='childcare_create'),
    url(r'^(?P<childcare_slug>[\w\-]+)/dashboard/', include('childcare.urls', namespace="childcare")),

    #website
    url(r'^(?P<childcare_slug>[\w\-]+)/', include('website.urls', namespace="website")),
)

# check if app is local or deployed on server
LOCAL_ENV_BOOL = is_local_env()

if LOCAL_ENV_BOOL:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

classroom/models.py
from django.db import models
from easy_thumbnails.fields import ThumbnailerField, ThumbnailerImageField
from easy_thumbnails.files import get_thumbnailer
from childcare.models import Childcare
from django.contrib.auth.models import User
from utils.imagegenerators import get_file_path


class Classroom(models.Model):
    name = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=255, blank=True)
    childcare = models.ForeignKey(Childcare, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)
    disabled = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return 'childcare/%s/classroom/%s' % (self.childcare.pk, self.pk)


class Diary(models.Model):
    author = models.ForeignKey(User, null=True)
    date = models.DateField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)
    classroom = models.ForeignKey(Classroom, null=True)
    content = models.TextField()

    class Meta:
        unique_together = ['classroom', 'date']

    def __unicode__(self):
        return str(self.date)


class DiaryImage(models.Model):
    image = models.ImageField(upload_to=get_file_path, null=True)
    thumbnail = models.CharField(max_length=255, null=True)
    diary = models.ForeignKey(Diary, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)
    uploader = models.ForeignKey(User, null=True)

classroom/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from guardian.decorators import permission_required_or_403
from childcare.models import Childcare
from classroom.forms import ClassroomCreateForm, DiaryCreateForm, AddDiaryImageForm, DiaryUpdateForm
from classroom.models import Classroom, Diary, DiaryImage
from django.db import IntegrityError
from utils.files_images import get_max_size_in_mb
from utils.imagegenerators import utils_generate_thumbnail

# setup logging
import logging
log = logging.getLogger("logentries")

log_prefix = '[kindylog]'


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def classroom_create(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    if request.method == 'POST':
        form = ClassroomCreateForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.childcare = childcare
            obj.save()
            form.save(commit=True)
            log.info(log_prefix+'Classroom created (childcare: %s, user: %s)' % (childcare.name, request.user))
            return HttpResponseRedirect(reverse('childcare:classroom_list', kwargs={'childcare_slug': childcare.slug}))
    else:
        form = ClassroomCreateForm()
    return render(request, 'classroom/classroom_create.html', {'form': form, 'childcare': childcare})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def diary_create(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    if request.method == 'POST':
        form = DiaryCreateForm(data=request.POST, childcare=childcare)
        if form.is_valid():
            try:
                obj = form.save(commit=False)
                obj.author = request.user
                obj.save()
                diary = form.save(commit=True)
                log.info(log_prefix+'Diary created (childcare: %s, user: %s)' % (childcare.name, request.user))
                return HttpResponseRedirect(reverse('childcare:diary_list', kwargs={'childcare_slug': childcare.slug}))
            except IntegrityError:
                return render(request, 'classroom/error_diary_already_written.html', {'childcare': childcare})
    else:
        form = DiaryCreateForm(childcare=childcare)
    return render(request, 'classroom/diary_create.html', {'form': form,
                                                           'childcare': childcare})


@login_required
@permission_required_or_403('childcare_view', (Childcare, 'slug', 'childcare_slug'))
def diary_section(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    classroom_list = Classroom.objects.filter(childcare=childcare)
    all_diary_list = Diary.objects.filter(classroom__in=classroom_list).order_by('-date')
    log.info(log_prefix+'Diary section (childcare: %s, user: %s)' % (childcare.name, request.user))

    paginator = Paginator(all_diary_list, 10)
    page = request.GET.get('page')

    try:
        diary_list = paginator.page(page)
    except PageNotAnInteger:
        diary_list = paginator.page(1)
    except EmptyPage:
        diary_list = paginator.page(paginator.num_pages)

    return render(request, 'classroom/diary_section.html', {'childcare': childcare,
                                                            'diary_list': diary_list})


@login_required
@permission_required_or_403('childcare_view', (Childcare, 'slug', 'childcare_slug'))
def diary_detail(request, childcare_slug, diary_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    diary = get_object_or_404(Diary, pk=diary_id)
    diary_image_list = DiaryImage.objects.filter(diary=diary)
    log.info(log_prefix+'Diary read (childcare: %s, user: %s)' % (childcare.name, request.user))
    return render(request, 'classroom/diary_detail.html', {'childcare': childcare,
                                                           'diary': diary,
                                                           'diary_image_list': diary_image_list})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def diary_update(request, childcare_slug, diary_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    diary = get_object_or_404(Diary, pk=diary_id)
    #ImageFormSet = formset_factory(DiaryImageUpdateForm, )
    if request.method == 'POST':
        form = DiaryUpdateForm(data=request.POST, instance=diary)
        if form.is_valid():
            form.save()
            log.info(log_prefix+'Diary updated (childcare: %s, user: %s)' % (childcare.name, request.user))
            return HttpResponseRedirect(reverse('childcare:diary_detail', kwargs={'childcare_slug': childcare.slug,
                                                                                  'diary_id': diary.pk}))
    else:
        form = DiaryUpdateForm(instance=diary)
    return render(request, 'classroom/diary_update.html', {'form': form,
                                                           'childcare': childcare,
                                                           'diary': diary})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def diary_delete(request, childcare_slug, diary_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    diary = get_object_or_404(Diary, pk=diary_id)
    if request.method == 'POST':
        diary.delete()
        log.info(log_prefix+'Diary deleted (childcare: %s, user: %s)' % (childcare.name, request.user))
        return HttpResponseRedirect(reverse('childcare:diary_list', kwargs={'childcare_slug': childcare.slug}))
    return render(request, 'classroom/diary_delete.html', {'childcare': childcare,
                                                           'diary': diary})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def add_diary_images(request, childcare_slug, diary_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    diary = get_object_or_404(Diary, pk=diary_id)
    image_size = get_max_size_in_mb()
    if request.method == 'POST':
        form = AddDiaryImageForm(request.POST, request.FILES)
        if form.is_valid():
            log.info(log_prefix+'Diary images added (childcare: %s, user: %s)' % (childcare.name, request.user))
            obj = form.save(commit=False)
            if obj.image:  # save only forms with images
                obj.diary = diary
                obj.uploader = request.user
                obj.save()
                object = form.save(commit=True)
                # generate thumbnail
                utils_generate_thumbnail(object)
                return HttpResponseRedirect(reverse('childcare:diary_detail', kwargs={'childcare_slug': childcare.slug,
                                                                                      'diary_id': diary.pk}))
    else:
        form = AddDiaryImageForm()
    return render(request, 'classroom/add_diary_image.html', {'form': form,
                                                              'childcare': childcare,
                                                              'image_size': image_size})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def diary_image_delete(request, childcare_slug, diary_id, image_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    diary_image = get_object_or_404(DiaryImage, pk=image_id, diary=diary_id)
    diary = get_object_or_404(Diary, pk=diary_id)
    if request.method == 'POST':
        diary_image.delete()
        log.info(log_prefix+'Diary image deleted (childcare: %s, user: %s)' % (childcare.name, request.user))
        return HttpResponseRedirect(reverse('childcare:diary_detail', kwargs={'childcare_slug': childcare.slug,
                                                                              'diary_id': diary.pk}))
    return render(request, 'classroom/diary_image_delete.html', {'childcare': childcare,
                                                                 'image': diary_image})


@login_required
@permission_required_or_403('childcare_view', (Childcare, 'slug', 'childcare_slug'))
def classroom_list(request, childcare_slug):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    all_classroom_list = Classroom.objects.filter(childcare=childcare, disabled=False)

    paginator = Paginator(all_classroom_list, 10)
    page = request.GET.get('page')

    try:
        classroom_list = paginator.page(page)
    except PageNotAnInteger:
        classroom_list = paginator.page(1)
    except EmptyPage:
        classroom_list = paginator.page(paginator.num_pages)

    return render(request, 'classroom/classroom_list.html', {'childcare': childcare,
                                                             'classroom_list': classroom_list})


@login_required
@permission_required_or_403('childcare_employee', (Childcare, 'slug', 'childcare_slug'))
def classroom_delete(request, childcare_slug, classroom_id):
    childcare = get_object_or_404(Childcare, slug=childcare_slug)
    classroom = get_object_or_404(Classroom, pk=classroom_id)
    if request.method == 'POST':
        classroom.disabled = True
        classroom.save()
        log.info(log_prefix+'Classroom deleted (childcare: %s, user: %s)' % (childcare.name, request.user))
        return HttpResponseRedirect(reverse('childcare:classroom_list', kwargs={'childcare_slug': childcare.slug}))

templates/classroom/classroom_list.html
{% extends 'childcare/childcare_base.html' %}

{% block title %}Classroom list{% endblock title %}

{% block action %}
    {% if user in childcare.employees.all or user in childcare.managers.all %}
        <li><a href="{% url 'childcare:classroom_create' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-plus"></span> Add classroom</a></li>
    {% endif %}
{% endblock %}

{% block content-title %}Classrooms{% endblock %}

{% block content %}
    {% if classroom_list %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>Classroom</th>
                <th>Description</th>
                {% if user in childcare.employees.all or user in childcare.managers.all %}
                <th>Tools</th>
                {% endif %}
            </tr>
            {% for classroom in classroom_list %}
                <tr>
                    <td>
                        {{ classroom }}
                    </td>
                    <td>
                        {{ classroom.description }}
                    </td>
                    {% if user in childcare.employees.all or user in childcare.managers.all %}
                    <td>
                        <a href="{% url 'childcare:classroom_update' childcare_slug=childcare.slug classroom_id=classroom.pk %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit"></span> Update</a>
                        <a href="{% url 'childcare:classroom_delete' childcare_slug=childcare.slug classroom_id=classroom.pk %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if classroom_list.has_previous %}
                <a href="?page={{ classroom_list.previous_page_number }}">previous</a>
            {% endif %}

            {% if classroom_list.has_other_pages %}
            <span class="current">
                Page {{ classroom_list.number }} of {{ classroom_list.paginator.num_pages }}
            </span>
            {% endif %}

            {% if classroom_list.has_next %}
                <a href="?page={{ classroom_list.next_page_number }}"> next</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <p>No classrooms.
        {% if user in childcare.employees.all or user in childcare.managers.all %}
            You need at least one to publish e-diaries.
            <a href="{% url 'childcare:classroom_create' childcare_slug=childcare.slug %}">Add a classroom.</a>
        {% endif %}</p>
    {% endif %}
{% endblock content %}

templates/classroom/diary_create.html
{% extends 'childcare/childcare_base.html' %}
{% load widget_tweaks %}

{% block title %}Create a diary{% endblock title %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/texteditor.css">
{% endblock %}

{% block content-title %}Create a diary{% endblock %}

{% block content %}
<form method="post" class="form-horizontal">
	{% csrf_token %}
	{% if form.non_field_errors %}
	<div class="alert alert-warning"><strong>Warning!</strong> {{ form.non_field_errors.as_text|cut:'* ' }}</div>
	{% endif %}
	{% for field in form %}
	<div class="form-group{% if field.errors %} has-error{% endif %}">
		<label class="col-md-1 control-label">{{ field.label }}</label>
		<div class="col-md-3">
			{% if field.name == 'date' %}
			<p class="form-control-static">{{ field }}</p>
			{% else %}
			{{ field|add_class:'form-control' }}
			{% endif %}

			{% if field.name == 'content' and field.errors %}
			<p>{{ field.errors.as_text }}</p>
			{% endif %}
		</div>
		{% if field.name != 'content' %}
		<div class="col-md-3">
			<p class="form-control-static">{{ field.errors.as_text }}</p>
		</div>
		{% endif %}
	</div>
	{% endfor %}
	<div class="form-group">
		<div class="col-md-2 col-md-offset-1">
			<input type="submit" value="Create" class="btn btn-success">
		</div>
	</div>
</form>
{% endblock %}

{% block footer %}
	<script type="text/javascript">
		texteditor('#id_content');
	</script>
{% endblock %}

templates/classroom/diary_delete.html
{% extends 'childcare/childcare_base.html' %}

{% block title %}Delete a diary{% endblock title %}

{% block content-title %}Delete a diary for {{ diary.date }}?{% endblock %}

{% block content %}
    <p>Are you sure you want to delete a diary for {{ diary.date }}?</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, I'm sure</button>
    </form>
{% endblock content %}

templates/classroom/diary_detail.html
{% extends 'childcare/childcare_base.html' %}
{% load thumbnail %}

{% block title %}A diary for {{ diary.date.day }} {{ diary.date|date:'M' }} {{ diary.date.year }}{% endblock title %}

{% block header %}
    {% if diary_image_list %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/fancybox.css">
    {% endif %}
{% endblock %}

{% block action %}
    {% if user in childcare.employees.all or user in childcare.managers.all %}
    <li><a href="{% url 'childcare:diary_add_images' childcare_slug=childcare.slug diary_id=diary.pk %}"><span class="glyphicon glyphicon-plus"></span> Add images</a></li>
    <li><a href="{% url 'childcare:diary_delete' childcare_slug=childcare.slug diary_id=diary.pk %}"><span class="glyphicon glyphicon-remove"></span> Delete</a></li>
    <li><a href="{% url 'childcare:diary_update' childcare_slug=childcare.slug diary_id=diary.pk %}"><span class="glyphicon glyphicon-edit"></span> Update</a></li>
    {% endif %}
{% endblock action %}

{% block content-title %}A diary for {{ diary.date.day }} {{ diary.date|date:'M' }} {{ diary.date.year }}{% endblock %}

{% block content %}
    <p><strong>{% if diary.author.first_name == '' %} {{ diary.author }}{% else %} {{ diary.author.get_full_name }}{% endif %} | {{ diary.classroom }}</strong></p>
    <p>{{ diary.content|safe }}</p>

    {% if diary_image_list %}
    <hr>
    <p><strong>Gallery</strong></p>
        {% for image in diary_image_list %}
            {% if image.image %}
                <div class="pull-left">

                    <a href="{{ image.image.url }}" class="fancybox" rel="gallery" title="Diary for {{ diary.date.day }} {{ diary.date|date:'M' }} {{ diary.date.year }}"><img src="{{ image.thumbnail }}"></a>

                    {% if user in childcare.employees.all or user in childcare.managers.all %}
                        <p><a href="{% url 'childcare:diary_image_delete' childcare_slug=childcare.slug diary_id=diary.pk image_id=image.pk %}"><span class="glyphicon glyphicon-remove"></span> Delete</a></p>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}
        <div class="clearfix"></div>
    {% else %}
        {% if user in childcare.employees.all or user in childcare.managers.all %}
        <hr>
        <p><strong>Gallery</strong></p>
        No images were added yet to this diary. <a href="{% url 'childcare:diary_add_images' childcare_slug=childcare.slug diary_id=diary.pk %}" class="btn btn-xs btn-default">Add images</a>
        {% endif %}
    {% endif %}
{% endblock content %}

{% block footer %}
    {% if diary_image_list %}
    <script type="text/javascript">
        gallery('a.fancybox');
    </script>
    {% endif %}
{% endblock %}

templates/classroom/diary_section.html
{% extends 'childcare/childcare_base.html' %}

{% block title %}Daily diary list{% endblock title %}

{% block action %}
    {% if user in childcare.employees.all or user in childcare.managers.all %}
    <li><a href="{% url 'childcare:diary_create' childcare_slug=childcare.slug %}"><span class="glyphicon glyphicon-plus"></span> Add a diary</a></li>
    {% endif %}
{% endblock %}

{% block content-title %}Daily diary list{% endblock content-title %}

{% block content %}
    {% if diary_list %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>Diary</th>
                <th>Classroom</th>
                {% if user in childcare.employees.all or user in childcare.managers.all %}
                <th>Tools</th>
                {% endif %}
            </tr>
            {% for diary in diary_list %}
                <tr>
                    <td>
                        <a href="{% url 'childcare:diary_detail' childcare_slug=childcare.slug diary_id=diary.pk %}">{{ diary.date.day }} {{ diary.date|date:'M' }} {{ diary.date.year }}</a>
                    </td>
                    <td>
                        {{ diary.classroom }}
                    </td>
                    {% if user in childcare.employees.all or user in childcare.managers.all %}
                    <td>
                        <a href="{% url 'childcare:diary_add_images' childcare_slug=childcare.slug diary_id=diary.pk %}" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-plus"></span> Add images</a>
                        <a href="{% url 'childcare:diary_update' childcare_slug=childcare.slug diary_id=diary.pk %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit"></span> Update</a>
                        <a href="{% url 'childcare:diary_delete' childcare_slug=childcare.slug diary_id=diary.pk %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if diary_list.has_previous %}
                <a href="?page={{ diary_list.previous_page_number }}">previous</a>
            {% endif %}

            {% if diary_list.has_other_pages %}
            <span class="current">
                Page {{ diary_list.number }} of {{ diary_list.paginator.num_pages }}
            </span>
            {% endif %}

            {% if diary_list.has_next %}
                <a href="?page={{ diary_list.next_page_number }}"> next</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <p>No diaries yet.
        {% if user in childcare.employees.all or user in childcare.managers.all %}
            <a href="{% url 'childcare:diary_create' childcare_slug=childcare.slug %}">Write your first e-diary!</a>
        {% endif %}</p>
    {% endif %}
{% endblock content %}

templates/classroom/diary_update.html
{% extends 'childcare/childcare_base.html' %}
{% load widget_tweaks %}

{% block title %}Update a diary{% endblock title %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/texteditor.css">
{% endblock %}

{% block content-title %}Update a diary{% endblock %}

{% block content %}
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js"></script>
<form method="post" class="form-horizontal">
	{% csrf_token %}
	{% for field in form %}
	<div class="form-group{% if field.errors %} has-error{% endif %}">
		<label class="col-md-1 control-label">{{ field.label }}</label>
		<div class="col-md-3">
			{{ field|add_class:'form-control' }}
		</div>
	</div>
	{% if field.errors %}
	<div class="form-group">
		<div class="col-md-3 col-md-offset-1">
			<p>{{ field.errors.as_text }}</p>
		</div>
	</div>
	{% endif %}
	{% endfor %}
	<div class="form-group">
		<div class="col-md-2 col-md-offset-1">
			<input type="submit" value="Update" class="btn btn-success">
		</div>
	</div>
</form>
{% endblock %}

{% block footer %}
	<script type="text/javascript">
		texteditor('#id_content');
	</script>
{% endblock %}