childcare/urls.py
from django.conf.urls import patterns, url
from childcare import views
from classroom import views as classroom_views
from newsboard import views as newsboard_views

urlpatterns = patterns('',
                       #childcare
                       url(r'^childcare/$', views.childcare, name='childcare_info'),
                       url(r'^childcare/update/$', views.childcare_update, name='childcare_update'),

                       #users
                       url(r'^childcare/users/invite/$', views.invite_users, name='invite_users'),
                       url(r'^childcare/managers/(?P<username>[\w\-]+)/remove/$', views.remove_manager, name='manager_remove'),
                       url(r'^childcare/employees/(?P<username>[\w\-]+)/remove/$', views.remove_employee, name='employee_remove'),
                       url(r'^childcare/parents/(?P<username>[\w\-]+)/remove/$', views.remove_parent, name='parent_remove'),
                       url(r'^childcare/managers/$', views.managers_list, name='manager_list'),
                       url(r'^childcare/employees/$', views.employees_list, name='employee_list'),
                       url(r'^childcare/parents/$', views.parents_list, name='parent_list'),

                       # classroom
                       url(r'^classroom/create/$', classroom_views.classroom_create, name='classroom_create'),
                       url(r'^classroom/$', classroom_views.classroom_list, name='classroom_list'),
                       url(r'^classroom/(?P<classroom_id>\d+)/delete/$', classroom_views.classroom_delete, name='classroom_delete'),
                       url(r'^classroom/(?P<classroom_id>\d+)/update/$', classroom_views.classroom_update, name='classroom_update'),

                       # diary
                       url(r'^diary/create/$', classroom_views.diary_create, name='diary_create'),
                       url(r'^diary/(?P<diary_id>\d+)/$', classroom_views.diary_detail, name='diary_detail'),
                       url(r'^diary/$', classroom_views.diary_section, name='diary_list'),
                       url(r'^diary/(?P<diary_id>\d+)/images/$', classroom_views.add_diary_images, name='diary_add_images'),
                       url(r'^diary/(?P<diary_id>\d+)/delete/$', classroom_views.diary_delete, name='diary_delete'),
                       url(r'^diary/(?P<diary_id>\d+)/update/$', classroom_views.diary_update, name='diary_update'),
                       url(r'^diary/(?P<diary_id>\d+)/image/(?P<image_id>\d+)/delete/$', classroom_views.diary_image_delete, name='diary_image_delete'),

                       # newsboard
                       url(r'^newsboard/create/$', newsboard_views.childcare_news_create, name='news_create'),
                       url(r'^newsboard/(?P<news_id>\d+)/$', newsboard_views.childcare_news_detail, name='news_detail'),
                       url(r'^newsboard/(?P<news_id>\d+)/images/$', newsboard_views.add_news_images, name='news_add_images'),
                       url(r'^newsboard/(?P<news_id>\d+)/files/$', newsboard_views.add_news_files, name='news_add_files'),
                       url(r'^newsboard/$', newsboard_views.newsboard_section, name='news_list'),
                       url(r'^newsboard/(?P<news_id>\d+)/delete/$', newsboard_views.childcare_news_delete, name='news_delete'),
                       url(r'^newsboard/(?P<news_id>\d+)/update/$', newsboard_views.childcare_news_update, name='news_update'),
                       url(r'^newsboard/(?P<news_id>\d+)/image/(?P<image_id>\d+)/delete/$', newsboard_views.news_image_delete, name='news_image_delete'),
                       url(r'^newsboard/(?P<news_id>\d+)/file/(?P<file_id>\d+)/delete/$', newsboard_views.news_file_delete, name='news_file_delete'),

                       # website
                       url(r'^website/page/create/$', views.website_page_create, name='page_create'),
                       url(r'^website/$', views.website_pages_list, name='page_list'),
                       url(r'^website/page/(?P<page_id>\d+)/files/$', views.add_page_files, name='page_add_files'),
                       url(r'^website/page/(?P<page_id>\d+)/delete/$', views.website_page_delete, name='page_delete'),
                       url(r'^website/page/(?P<page_id>\d+)/update/$', views.website_page_update, name='page_update'),
                       url(r'^website/page/(?P<page_id>\d+)/file/(?P<file_id>\d+)/delete/$', views.page_file_delete, name='page_file_delete'),
                       url(r'^website/page/about/edit/$', views.website_first_page_edit, name='about_edit'),
                       url(r'^website/theme/$', views.website_choose_theme, name='choose_theme'),

                       # gallery
                       url(r'^gallery/$', views.gallery_section, name='gallery'),
                       )

kindy/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from childcare import views as childcare_views
from django.conf import settings
from utils.deployment import is_local_env
from userena import views as userena_views

admin.autodiscover()

urlpatterns = patterns('',

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # home
    url(r'^$', 'kindy.views.home', name='home'),

    # accounts
    url(r'^accounts/', include('userena.urls')),
    url(r'^activate/(?P<activation_key>\w+)/$', userena_views.activate, {'success_url': '/'}, name='userena_activate'),

    #childcare
    url(r'^childcare/create/$', childcare_views.childcare_create, name='childcare_create'),
    url(r'^(?P<childcare_slug>[\w\-]+)/dashboard/', include('childcare.urls', namespace="childcare")),

    #website
    url(r'^(?P<childcare_slug>[\w\-]+)/', include('website.urls', namespace="website")),
)

# check if app is local or deployed on server
LOCAL_ENV_BOOL = is_local_env()

if LOCAL_ENV_BOOL:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

kindy/views.py
from itertools import chain
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, render_to_response
from childcare.models import Childcare


@login_required
def home(request):
    childcare_list_manager = Childcare.objects.filter(managers__id=request.user.pk)
    childcare_list_employee = Childcare.objects.filter(employees__id=request.user.pk)
    childcare_list_parent = Childcare.objects.filter(parents__id=request.user.pk)

    all_childcare_list = list(set(chain(childcare_list_manager, childcare_list_employee, childcare_list_parent)))  # set for removing duplicates, chain for chaining lists
    return render(request, 'kindy/home.html', {'all_childcare_list': all_childcare_list})

templates/kindy/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}{% endblock %} | Kindy - child care management system</title>
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/kindy.css">
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jscrollpane.css">
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
		<link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.png">
		{% block header %}{% endblock %}
		<script type="text/javascript">
		// <![CDATA[
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
			ga('create', 'UA-47090236-1', 'kindy.at');
			ga('send', 'pageview');
		// ]]>
		</script>
	</head>
	<body>
		<div id="header">
			<div class="sidebar-button visible-xs visible-sm"><span class="glyphicon glyphicon-align-justify"></span></div>
			<a href="/" class="logo"><img src="{{ STATIC_URL }}img/logo.png" alt="Kindy"></a>
			<div class="hidden-xs">
				{% if childcare %}
				<p class="pull-left"><span class="name">{{ childcare }}</span> | <a href="/{{ childcare.slug }}/" target="_blank">Go to website</a></p>
				{% endif %}
				<p class="pull-right">
					<span class="glyphicon glyphicon-home"></span> <a href="/">Home</a> |
				{% if user.is_authenticated %}
					<span class="glyphicon glyphicon-user"></span> <a href="/accounts/{{ user }}">{% if user.first_name == '' %}{{ user }}{% else %}{{ user.first_name }} {{ user.last_name }}{% endif %}</a> |
					<span class="glyphicon glyphicon-log-out"></span> <a href="/accounts/signout/">Logout</a>
				{% else %}
					<span class="glyphicon glyphicon-log-in"></span> <a href="/accounts/signin/">Login</a>
				{% endif %}
				</p>
			</div>
		</div>
		<div id="sidebar">
			<p class="name">{% block sidebar-title %}{% endblock %}</p>
			<ul class="nav">
				{% block sidebar %}{% endblock %}
			</ul>
		</div>
		<div id="content">
			<div class="padding">
				<div class="nav">
					<p class="title">{% block content-title %}{% endblock %}</p>
					<ul class="nav navbar-nav actions">
						{% block action %}{% endblock action %}
					</ul>
				</div>
				{% block content %}{% endblock %}
			</div>
		</div>
		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/retina.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/mousewheel.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/jscrollpane.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/functions.js"></script>
		<script type="text/javascript">
			$(function() {
				if('{{ request.path }}' != '/') {
					$('#sidebar ul.nav a').each(function() {
						if('{{ request.path }}'.match($(this).attr('href')) && $(this).attr('href') != '/') $(this).addClass('active');
					});
				} else {
					$('#sidebar ul.nav a[href="/"]').addClass('active');
				}
			});
		</script>
		{% block footer %}{% endblock %}
	</body>
</html>

templates/kindy/home.html
{% extends 'kindy/base.html' %}

{% block title %}Home{% endblock %}

{% block sidebar-title %}Home{% endblock %}

{% block sidebar %}
    <li><a href="/"><span class="glyphicon glyphicon-home"></span>Home</a></li>
    <li><a href="/accounts/{{ user.username }}/"><span class="glyphicon glyphicon-user"></span>My profile</a></li>
    <li><a href="/childcare/create/"><span class="glyphicon glyphicon-plus"></span>Create childcare</a></li>
{% endblock %}

{% block content-title %}
    Hello{% if user.first_name == '' %} {{ user }}{% else %} {{ user.get_full_name }}{% endif %}!
{% endblock %}

{% block content %}
    <div class="row">
        {% if all_childcare_list %}
            {% for childcare in all_childcare_list %}
            <div class="col-xs-12 col-sm-6 col-md-4 info-box">
                <a href="{% url 'childcare:childcare_info' childcare_slug=childcare.slug %}" class="panel static">
                    <span class="glyphicon glyphicon-home"></span><br>{{ childcare }}
                </a>
            </div>
            {% endfor %}
        {% endif %}
        <div class="col-xs-12 col-sm-6 col-md-4 info-box">
            <a href="/childcare/create/" class="panel static"{% if all_childcare_list %} style="opacity:0.9;"{% endif %}>
                <span class="glyphicon glyphicon-plus"></span><br>Create childcare
            </a>
        </div>
    </div>
{% endblock %}